version: "3"
services:
  prometheus:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - prometheus-storage:/prometheus
  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  node_to_prometheus:
    build: ./src
    ports:
      - "4000:4000"
  prometheus_exporter:
    build: ./prometheus-exporter
    ports:
      - "7979:7979"
volumes:
  prometheus-storage:
  grafana-storage:
